# Site settings
title: zld's world
email: 674737109@qq.com
description: 记录假期时光# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yunzhongguo.github.io/creative-theme-jekyll/" # the base hostname & protocol for your site

twitter_username:
github_username: yunzhongguo

# Build settings
markdown: kramdown
